.PHONY: test
test:
	$(MAKE) test -C contracts
	$(MAKE) test -C templates

.PHONY: generate
generate:
	$(MAKE) generate -C contracts
	$(MAKE) generate -C templates

.PHONY: ci
ci:
	$(MAKE) ci -C contracts
	$(MAKE) ci -C templates